config/routes.rb
Rails.application.routes.draw do
  resources :payment_projects
  resources :fellow_ships_students
  resources :fellow_ships_employees
  resources :projects
  resources :editals
  resources :banks
  resources :students
  resources :employees
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fellow_ships_employee.rb
class FellowShipsEmployee < ApplicationRecord
  belongs_to :employee
  belongs_to :bank
  belongs_to :project
end

app/controllers/fellow_ships_employees_controller.rb
class FellowShipsEmployeesController < ApplicationController
  before_action :set_fellow_ships_employee, only: [:show, :edit, :update, :destroy]

  # GET /fellow_ships_employees
  # GET /fellow_ships_employees.json
  def index
    @fellow_ships_employees = FellowShipsEmployee.all
  end

  # GET /fellow_ships_employees/1
  # GET /fellow_ships_employees/1.json
  def show
  end

  # GET /fellow_ships_employees/new
  def new
    @fellow_ships_employee = FellowShipsEmployee.new
  end

  # GET /fellow_ships_employees/1/edit
  def edit
  end

  # POST /fellow_ships_employees
  # POST /fellow_ships_employees.json
  def create
    @fellow_ships_employee = FellowShipsEmployee.new(fellow_ships_employee_params)

    respond_to do |format|
      if @fellow_ships_employee.save
        format.html { redirect_to @fellow_ships_employee, notice: 'Fellow ships employee was successfully created.' }
        format.json { render :show, status: :created, location: @fellow_ships_employee }
      else
        format.html { render :new }
        format.json { render json: @fellow_ships_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fellow_ships_employees/1
  # PATCH/PUT /fellow_ships_employees/1.json
  def update
    respond_to do |format|
      if @fellow_ships_employee.update(fellow_ships_employee_params)
        format.html { redirect_to @fellow_ships_employee, notice: 'Fellow ships employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @fellow_ships_employee }
      else
        format.html { render :edit }
        format.json { render json: @fellow_ships_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fellow_ships_employees/1
  # DELETE /fellow_ships_employees/1.json
  def destroy
    @fellow_ships_employee.destroy
    respond_to do |format|
      format.html { redirect_to fellow_ships_employees_url, notice: 'Fellow ships employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fellow_ships_employee
      @fellow_ships_employee = FellowShipsEmployee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fellow_ships_employee_params
      params.require(:fellow_ships_employee).permit(:employee_id, :cpf, :bank_id, :project_id)
    end
end

app/helpers/fellow_ships_employees_helper.rb
module FellowShipsEmployeesHelper
end

app/views/fellow_ships_employees/_form.html.erb
<%= simple_form_for(@fellow_ships_employee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :employee %>
    <%= f.input :cpf %>
    <%= f.association :bank %>
    <%= f.association :project %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fellow_ships_employees/edit.html.erb
<h1>Editing Fellow Ships Employee</h1>

<%= render 'form', fellow_ships_employee: @fellow_ships_employee %>

<%= link_to 'Show', @fellow_ships_employee %> |
<%= link_to 'Back', fellow_ships_employees_path %>

app/views/fellow_ships_employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fellow Ships Employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Cpf</th>
      <th>Bank</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fellow_ships_employees.each do |fellow_ships_employee| %>
      <tr>
        <td><%= fellow_ships_employee.employee %></td>
        <td><%= fellow_ships_employee.cpf %></td>
        <td><%= fellow_ships_employee.bank %></td>
        <td><%= fellow_ships_employee.project %></td>
        <td><%= link_to 'Show', fellow_ships_employee %></td>
        <td><%= link_to 'Edit', edit_fellow_ships_employee_path(fellow_ships_employee) %></td>
        <td><%= link_to 'Destroy', fellow_ships_employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fellow Ships Employee', new_fellow_ships_employee_path %>

app/views/fellow_ships_employees/new.html.erb
<h1>New Fellow Ships Employee</h1>

<%= render 'form', fellow_ships_employee: @fellow_ships_employee %>

<%= link_to 'Back', fellow_ships_employees_path %>

app/views/fellow_ships_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @fellow_ships_employee.employee %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @fellow_ships_employee.cpf %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @fellow_ships_employee.bank %>
</p>

<p>
  <strong>Project:</strong>
  <%= @fellow_ships_employee.project %>
</p>

<%= link_to 'Edit', edit_fellow_ships_employee_path(@fellow_ships_employee) %> |
<%= link_to 'Back', fellow_ships_employees_path %>