config/routes.rb
Rails.application.routes.draw do
  resources :payment_projects
  resources :fellow_ships_students
  resources :fellow_ships_employees
  resources :projects
  resources :editals
  resources :banks
  resources :students
  resources :employees
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment_project.rb
class PaymentProject < ApplicationRecord
  belongs_to :project
  belongs_to :employee
end

app/controllers/payment_projects_controller.rb
class PaymentProjectsController < ApplicationController
  before_action :set_payment_project, only: [:show, :edit, :update, :destroy]

  # GET /payment_projects
  # GET /payment_projects.json
  def index
    @payment_projects = PaymentProject.all
  end

  # GET /payment_projects/1
  # GET /payment_projects/1.json
  def show
  end

  # GET /payment_projects/new
  def new
    @payment_project = PaymentProject.new
  end

  # GET /payment_projects/1/edit
  def edit
  end

  # POST /payment_projects
  # POST /payment_projects.json
  def create
    @payment_project = PaymentProject.new(payment_project_params)

    respond_to do |format|
      if @payment_project.save
        format.html { redirect_to @payment_project, notice: 'Payment project was successfully created.' }
        format.json { render :show, status: :created, location: @payment_project }
      else
        format.html { render :new }
        format.json { render json: @payment_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_projects/1
  # PATCH/PUT /payment_projects/1.json
  def update
    respond_to do |format|
      if @payment_project.update(payment_project_params)
        format.html { redirect_to @payment_project, notice: 'Payment project was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_project }
      else
        format.html { render :edit }
        format.json { render json: @payment_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_projects/1
  # DELETE /payment_projects/1.json
  def destroy
    @payment_project.destroy
    respond_to do |format|
      format.html { redirect_to payment_projects_url, notice: 'Payment project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_project
      @payment_project = PaymentProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_project_params
      params.require(:payment_project).permit(:project_id, :employee_id, :process, :date_payment, :date_start, :date_end)
    end
end

app/helpers/payment_projects_helper.rb
module PaymentProjectsHelper
end

app/views/payment_projects/_form.html.erb
<%= simple_form_for(@payment_project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :project %>
    <%= f.association :employee %>
    <%= f.input :process %>
    <%= f.input :date_payment %>
    <%= f.input :date_start %>
    <%= f.input :date_end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_projects/edit.html.erb
<h1>Editing Payment Project</h1>

<%= render 'form', payment_project: @payment_project %>

<%= link_to 'Show', @payment_project %> |
<%= link_to 'Back', payment_projects_path %>

app/views/payment_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Projects</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Employee</th>
      <th>Process</th>
      <th>Date payment</th>
      <th>Date start</th>
      <th>Date end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_projects.each do |payment_project| %>
      <tr>
        <td><%= payment_project.project %></td>
        <td><%= payment_project.employee %></td>
        <td><%= payment_project.process %></td>
        <td><%= payment_project.date_payment %></td>
        <td><%= payment_project.date_start %></td>
        <td><%= payment_project.date_end %></td>
        <td><%= link_to 'Show', payment_project %></td>
        <td><%= link_to 'Edit', edit_payment_project_path(payment_project) %></td>
        <td><%= link_to 'Destroy', payment_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Project', new_payment_project_path %>

app/views/payment_projects/new.html.erb
<h1>New Payment Project</h1>

<%= render 'form', payment_project: @payment_project %>

<%= link_to 'Back', payment_projects_path %>

app/views/payment_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @payment_project.project %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @payment_project.employee %>
</p>

<p>
  <strong>Process:</strong>
  <%= @payment_project.process %>
</p>

<p>
  <strong>Date payment:</strong>
  <%= @payment_project.date_payment %>
</p>

<p>
  <strong>Date start:</strong>
  <%= @payment_project.date_start %>
</p>

<p>
  <strong>Date end:</strong>
  <%= @payment_project.date_end %>
</p>

<%= link_to 'Edit', edit_payment_project_path(@payment_project) %> |
<%= link_to 'Back', payment_projects_path %>