config/routes.rb
Rails.application.routes.draw do
  resources :payment_projects
  resources :fellow_ships_students
  resources :fellow_ships_employees
  resources :projects
  resources :editals
  resources :banks
  resources :students
  resources :employees
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
  validates :name, :code, presence: true
  validates :code, numericality: true

end

app/models/edital.rb
class Edital < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/fellow_ships_employee.rb
class FellowShipsEmployee < ApplicationRecord
  belongs_to :employee
  belongs_to :bank
  belongs_to :project
end

app/models/fellow_ships_student.rb
class FellowShipsStudent < ApplicationRecord
  belongs_to :student
  belongs_to :bank
  belongs_to :project
end

app/models/payment_project.rb
class PaymentProject < ApplicationRecord
  belongs_to :project
  belongs_to :employee
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :employee
  belongs_to :edital
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:code, :name)
    end
end

app/controllers/editals_controller.rb
class EditalsController < ApplicationController
  before_action :set_edital, only: [:show, :edit, :update, :destroy]

  # GET /editals
  # GET /editals.json
  def index
    @editals = Edital.all
  end

  # GET /editals/1
  # GET /editals/1.json
  def show
  end

  # GET /editals/new
  def new
    @edital = Edital.new
  end

  # GET /editals/1/edit
  def edit
  end

  # POST /editals
  # POST /editals.json
  def create
    @edital = Edital.new(edital_params)

    respond_to do |format|
      if @edital.save
        format.html { redirect_to @edital, notice: 'Edital was successfully created.' }
        format.json { render :show, status: :created, location: @edital }
      else
        format.html { render :new }
        format.json { render json: @edital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editals/1
  # PATCH/PUT /editals/1.json
  def update
    respond_to do |format|
      if @edital.update(edital_params)
        format.html { redirect_to @edital, notice: 'Edital was successfully updated.' }
        format.json { render :show, status: :ok, location: @edital }
      else
        format.html { render :edit }
        format.json { render json: @edital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editals/1
  # DELETE /editals/1.json
  def destroy
    @edital.destroy
    respond_to do |format|
      format.html { redirect_to editals_url, notice: 'Edital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edital
      @edital = Edital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edital_params
      params.require(:edital).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/editals_helper.rb
module EditalsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Copeinca</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Fixed navbar -->
   <nav class="navbar navbar-default navbar-fixed-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">COPEIN/CA</a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
           <li> <%= link_to t(Employee.model_name.human.pluralize), employees_path %></li>
           <li><%= link_to t(Bank.model_name.human.pluralize), banks_path %></li>
           <li><%= link_to t(Project.model_name.human.pluralize), projects_path %></li>
           <li><%= link_to t(Edital.model_name.human.pluralize), editals_path %></li>

           <li><a href="#contact">Alunos</a></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projetos <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><a href="#">Listar</a></li>
               <li><a href="#">Indicar Bolsista</a></li>
               <li><a href="#">Despachos</a></li>

             </ul>
           </li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administração <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><a href="#">Usuários</a></li>
               <li><a href="#">Perfis</a></li>


             </ul>
           </li>
         </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>
   <div class="container theme-showcase" role="main">

    <%= yield %>

  </div>
  </body>
</html>